import { Preset } from './types';

export const builtInPresets: Preset[] = [
  {
    id: 'h264-web',
    name: 'H.264 — Web Delivery',
    description: 'MP4 H.264, CRF 18, AAC 192k. Great for web uploads and client delivery.',
    options: {
      videoCodec: 'libx264',
      audioCodec: 'aac',
      container: 'mp4',
      crf: 18,
      audioBitrate: '192k',
      hwAccel: 'none',
    },
    createdAt: '2026-01-01T00:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'h264-fast',
    name: 'H.264 — Fast / Draft',
    description: 'Quick encode for previews and rough cuts. CRF 23.',
    options: {
      videoCodec: 'libx264',
      audioCodec: 'aac',
      container: 'mp4',
      crf: 23,
      audioBitrate: '128k',
      hwAccel: 'none',
      extraArgs: ['-preset', 'veryfast'],
    },
    createdAt: '2026-01-01T00:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'h265-high',
    name: 'H.265 (HEVC) — High Quality',
    description: 'HEVC with CRF 20. Smaller files, excellent quality. Slower encode.',
    options: {
      videoCodec: 'libx265',
      audioCodec: 'aac',
      container: 'mp4',
      crf: 20,
      audioBitrate: '192k',
      hwAccel: 'none',
    },
    createdAt: '2026-01-01T00:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'prores-422-hq',
    name: 'ProRes 422 HQ',
    description: 'Apple ProRes 422 HQ in MOV. Ideal for DaVinci Resolve, Final Cut, Premiere.',
    options: {
      videoCodec: 'prores_ks',
      audioCodec: 'pcm_s24le',
      container: 'mov',
      proresProfile: '3',
      hwAccel: 'none',
    },
    createdAt: '2026-01-01T00:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'prores-4444',
    name: 'ProRes 4444',
    description: 'Apple ProRes 4444 with alpha support. For compositing and VFX.',
    options: {
      videoCodec: 'prores_ks',
      audioCodec: 'pcm_s24le',
      container: 'mov',
      proresProfile: '4',
      hwAccel: 'none',
    },
    createdAt: '2026-01-01T00:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'dnxhd-1080',
    name: 'DNxHD 1080p',
    description: 'Avid DNxHD for broadcast and Avid workflows.',
    options: {
      videoCodec: 'dnxhd',
      audioCodec: 'pcm_s16le',
      container: 'mxf',
      videoBitrate: '185M',
      hwAccel: 'none',
    },
    createdAt: '2026-01-01T00:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'audio-wav',
    name: 'Extract Audio — WAV',
    description: 'Extract audio as uncompressed 24-bit WAV.',
    options: {
      videoCodec: 'copy',
      audioCodec: 'pcm_s24le',
      container: 'wav',
      hwAccel: 'none',
    },
    createdAt: '2026-01-01T00:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'audio-mp3',
    name: 'Extract Audio — MP3 320k',
    description: 'Extract audio as high-quality MP3.',
    options: {
      videoCodec: 'copy',
      audioCodec: 'libmp3lame',
      container: 'mp3',
      audioBitrate: '320k',
      hwAccel: 'none',
    },
    createdAt: '2026-01-01T00:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'audio-aac',
    name: 'Extract Audio — AAC 256k',
    description: 'Extract audio as AAC in MP4 container.',
    options: {
      videoCodec: 'copy',
      audioCodec: 'aac',
      container: 'mp4',
      audioBitrate: '256k',
      hwAccel: 'none',
    },
    createdAt: '2026-01-01T00:00:00Z',
    isBuiltIn: true,
  },
];
